### ISSUE TITLE
Enhance merge-maven-repos to work with SNAPSHOT builds

### ISSUE THREAD

**Issue by dantran** [mojohaus/wagon-maven-plugin#7]
see https://issues.apache.org/jira/browse/WAGON-411

**Comment by tchemit** [comment]
@dantran Is there anything I can do to make this works ?

**Comment by Gohla** [comment]
Is there any progress on this? I'm also using merge-maven-repos to deploy a bunch of snapshot artifacts in one batch, which are produced from doing multiple Maven builds, but run into the problem of wrong maven-metadata.xml files.

Is this related to https://issues.apache.org/jira/browse/MDEPLOY-221, which was fixed in https://issues.apache.org/jira/browse/MNG-6240?

**Comment by jakub-bochenski** [comment]
@Gohla you might be interested in this workaround: https://github.com/mojohaus/wagon-maven-plugin/issues/9#issuecomment-380806127

**Comment by kwin** [comment]
This is IMHO blocked by https://issues.apache.org/jira/browse/MNG-5180.
